# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: true
sudo: false
cache: packages

#addons:
#    apt:
#        packages:
#            - libudunits2-dev

matrix:
    include:
        - os: linux
          r: release
          dist: trusty # 14.04
          env:
           - BUILD_NAME=trusty_release
           - DETAILS="release build"
           - USE_CXX11=yes
        - os: osx
          r: release
          env:
           - BUILD_NAME=osx_release
           - DETAILS="release build"
           - USE_CXX11=yes


after_success:
  - Rscript -e 'covr::codecov()'
